export const chatTypes = [
  "rap battle",
  "love song",
  "interview",
  "debate",
  "argument",
  "comedy skit",
];
export const sampleItems = [
  "Trump",
  "Tupac",
  "Liz Taylor",
  "Ghandi",
  "a cat",
  "Obama",
  "Churchill",
  "a gangster",
  "Malcolm X",
  "Eric Cartman",
  "Taylor Swift",
];
export const people: string[] = [
  "Abraham Lincoln",
  "Albert Einstein",
  "Alexander the Great",
  "Amelia Earhart",
  "Barack Obama",
  "Benjamin Franklin",
  "Beyoncé",
  "Bruce Wayne",
  "Che Guevara",
  "Cleopatra",
  "Darth Vader",
  "Don Quixote",
  "Donald Trump",
  "Dr. Strange",
  "Elon Musk",
  "Frida Kahlo",
  "Frodo Baggins",
  "Galileo Galilei",
  "Harry Potter",
  "Hermione Granger",
  "Homer Simpson",
  "Isaac Newton",
  "Joan of Arc",
  "Julius Caesar",
  "Katniss Everdeen",
  "Lady Gaga",
  "Leonardo da Vinci",
  "Luke Skywalker",
  "Malala Yousafzai",
  "Marie Curie",
  "Marilyn Monroe",
  "Martin Luther King Jr.",
  "Mahatma Gandhi",
  "Michael Jackson",
  "Napoleon Bonaparte",
  "Nelson Mandela",
  "Oprah Winfrey",
  "Pablo Picasso",
  "Princess Diana",
  "Queen Elizabeth II",
  "Rosa Parks",
  "Sherlock Holmes",
  "Simone Biles",
  "Socrates",
  "Spock",
  "Steve Jobs",
  "Taylor Swift",
  "The Joker",
  "Batman",
  "Tony Stark",
  "Tupac Shakur",
  "Winston Churchill",
];
